//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAMInsuranceBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim
    {
        public int Id { get; set; }
        public int PId { get; set; }
        public string Claim_Number { get; set; }
        public System.DateTime Claim_Date { get; set; }
        public string Status { get; set; }
    
        public virtual accident accident { get; set; }
        public virtual policy policy { get; set; }
        public virtual driver driver { get; set; }
        public virtual theft theft { get; set; }
        public virtual third_party third_party { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
