//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAMInsuranceBot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accident> accidents { get; set; }
        public virtual DbSet<claim> claims { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<policy> policies { get; set; }
        public virtual DbSet<renew> renews { get; set; }
        public virtual DbSet<theft> thefts { get; set; }
        public virtual DbSet<third_party> third_party { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
        public virtual DbSet<verification> verifications { get; set; }
    }
}
