//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAMInsuranceBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public policy()
        {
            this.claims = new HashSet<claim>();
            this.renews = new HashSet<renew>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Policy_Number { get; set; }
        public string Policy_Type { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Date_of_Expiration { get; set; }
        public bool Claim_Filed { get; set; }
        public bool Renew_Filed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claims { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<renew> renews { get; set; }
    }
}
