//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAMInsuranceBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verification
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string otp { get; set; }
        public bool ver_status { get; set; }
        public System.DateTime time_stamp { get; set; }
    
        public virtual client client { get; set; }
    }
}
